version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - mypostgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@mypostgres:5432/auth_db?schema=public
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./:/app
    restart: unless-stopped
  mypostgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: