services:
  submission-judge:
    container_name: submission-judge-app
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on: 
      - mongo 
    volumes:
      - .:/app
  mongo: 
    container_name: submission-judge-db
    image: mongo
    restart: always
    environment:
    #   MONGO_INITDB_ROOT_USERNAME: root 
    #   MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: submissionjudgedb 
    ports:
      - '37017:27017'
    volumes:
      - ./submission-judge-db-data:/data/db
